Array Creation(Numpy)





In [1]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4,5,6,7])
print(arr)

[1 2 3 4 5 6 7]


In [5]:
zeros_array=np.zeros(3)
print(zeros_array)

[0. 0. 0.]


In [7]:
ones_array=np.zeros((4,3))
print(ones_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
arr=np.arange(1,10,2)
print(arr)

[1 3 5 7 9]


In [17]:
arr=np.linspace(1,100,50)
print(arr)

[  1.           3.02040816   5.04081633   7.06122449   9.08163265
  11.10204082  13.12244898  15.14285714  17.16326531  19.18367347
  21.20408163  23.2244898   25.24489796  27.26530612  29.28571429
  31.30612245  33.32653061  35.34693878  37.36734694  39.3877551
  41.40816327  43.42857143  45.44897959  47.46938776  49.48979592
  51.51020408  53.53061224  55.55102041  57.57142857  59.59183673
  61.6122449   63.63265306  65.65306122  67.67346939  69.69387755
  71.71428571  73.73469388  75.75510204  77.7755102   79.79591837
  81.81632653  83.83673469  85.85714286  87.87755102  89.89795918
  91.91836735  93.93877551  95.95918367  97.97959184 100.        ]


In [19]:
arr=np.eye(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [20]:
arr=np.full(2,10)
print(arr)

[10 10]


In [23]:
arr=np.empty(100)
print(arr)

[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 1.]


Array Operations

In [25]:
arr=np.add(1,10)
print(arr)

11


In [27]:
arr=np.subtract(1,10)
print(arr)

-9


In [28]:
arr=np.multiply(10,2)
print(arr)

20


In [29]:
arr=np.divide(10,2)
print(arr)

5.0


In [31]:
arr=np.sqrt(9)
print(arr)

3.0


In [32]:
arr=np.power(9,2)
print(arr)

81


In [38]:
arr=np.mod(6,7)
print(arr)

6


In [40]:
arr=np.clip(4,1,12)
print(arr)

4


Statistical Functions

In [43]:
a=[1,2,3,4,5,6]
arr=np.mean(a)
print(arr)

3.5


In [44]:
a=[1,2,3,4,5,6]
arr=np.median(a)
print(arr)

3.5


In [45]:
a=[1,2,3,4,5,6]
arr=np.std(a)
print(arr)

1.707825127659933


In [46]:
a=[1,2,3,4,5,6]
arr=np.var(a)
print(arr)

2.9166666666666665


In [47]:
a=[1,2,3,4,5,6]
arr=np.min(a)
print(arr)

1


In [48]:
a=[1,2,3,4,5,6]
arr=np.max(a)
print(arr)

6


In [51]:
a=[1,2,3,4,5,6]
arr=np.percentile(a,25)
print(arr)

2.25


In [63]:
a=[1,5,6,4,5,6]
w=[1,2,6,1,7,1] # Example: weights now match the length of a
arr=np.average( a,weights=w,)
print(arr)

5.111111111111111


Aggregate Functions

In [64]:
a=[1,2,3,4,5,6]
arr=np.sum(a)
print(arr)

21


In [65]:
a=[1,2,3,4,5,6]
arr=np.prod(a)
print(arr)

720


In [66]:
a=[1,2,3,4,5,6]
arr=np.cumsum(a)
print(arr)

[ 1  3  6 10 15 21]


In [67]:
a=[1,2,3,4,5,6]
arr=np.cumprod(a)
print(arr)

[  1   2   6  24 120 720]


In [68]:
a=[1,2,3,4,5,6]
arr=np.argmax(a)
print(arr)

5


In [69]:
a=[1,2,3,4,5,6]
arr=np.argmin(a)
print(arr)

0


In [73]:
a=[1,2,9,4,5,6]
arr=np.all(a)
print(arr)

True


In [74]:
a=[1,2,3,4,5,6]
arr=np.any(a)
print(arr)

True


Linear Algebra

In [82]:

arr=np.dot(2,4)
print(arr)

8


In [77]:
a=[1,2,3,4,5,6]
b=[2,3,4,6,7,8]
arr=np.matmul(a,b)
print(arr)

127


In [84]:
a=np.array([[1,2],[3,4]])
arr=np.linalg.inv(a)
print(arr)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [86]:
a=np.array([[2,3],[4,5]])
arr=np.linalg.det(a)
print(arr)

-2.0


In [87]:
a=np.array([[2,3],[4,5]])
arr=np.linalg.eig(a)
print(arr)

EigResult(eigenvalues=array([-0.27491722,  7.27491722]), eigenvectors=array([[-0.79681209, -0.49436913],
       [ 0.60422718, -0.86925207]]))


In [88]:
a=np.array([[2,3],[4,5]])
arr=np.linalg.norm(a)
print(arr)

7.3484692283495345


In [89]:
a=np.array([[2,3],[4,5]])
arr=np.linalg.qr(a)
print(arr)

QRResult(Q=array([[-0.4472136 , -0.89442719],
       [-0.89442719,  0.4472136 ]]), R=array([[-4.47213595, -5.81377674],
       [ 0.        , -0.4472136 ]]))


In [90]:
a=np.array([[2,3],[4,5]])
arr=np.linalg.svd(a)
print(arr)

SVDResult(U=array([[-0.48992502, -0.87176457],
       [-0.87176457,  0.48992502]]), S=array([7.34342046, 0.27235265]), Vh=array([[-0.60828716, -0.79371704],
       [ 0.79371704, -0.60828716]]))


Random Operations

In [95]:
a=np.array([[2,3],[4,5]])
arr=np.random.rand()
print(arr)

0.20759501446510287


In [99]:
a=np.array([[2,3],[4,5]])
arr=np.random.randint(2,5)
print(arr)

2


In [104]:

mean = 2,4,5
std = 1,8,5
arr=np.random.normal(mean,std)
print(arr)

[ 1.33225359 13.09209649  9.91230599]


In [107]:
a=np.array([2,3,4,5])
arr=np.random.choice(a)
print(arr)

5


In [112]:
a=np.array([2,3,4,5])
arr=np.random.shuffle(a)
print(arr)

None


In [114]:
a=np.array([[2,3],[4,5]])
arr=np.random.seed()
print(arr)

None


In [115]:
a=np.array([[2,3],[4,5]])
arr=np.random.uniform()
print(arr)

0.9379180225885262


In [117]:
a=np.array([2,3,4,5])
arr=np.random.poisson()
print(arr)

0


Shape Operations

In [122]:
a=np.array([2,6,3,5,2,9,3,1])
arr=np.reshape(a,(2,4))
print(arr)

[[2 6 3 5]
 [2 9 3 1]]


In [132]:
a=np.array([[2,3],[4,5]])
arr=a.flatten()
print(arr)

[2 3 4 5]


In [133]:
a=np.array([[2,3],[4,5]])
arr=a.transpose()
print(arr)

[[2 4]
 [3 5]]


In [137]:
a=np.array([[2,3],[4,5]])
arr=a.resize()
print(arr)

None


In [141]:
a=np.array([[2,3],[4,5]])
arr=np.expand_dims(a, axis=2)
print(arr)

[[[2]
  [3]]

 [[4]
  [5]]]


In [142]:
a=np.array([[2,3],[4,5]])
arr=a.squeeze()
print(arr)

[[2 3]
 [4 5]]


In [144]:
a=np.array([[2,3],[4,5]])
arr=a.ravel()
print(arr)

[2 3 4 5]


In [153]:
a=np.array([2,3,4,5])
arr=np.hstack(a)
print(arr)

[2 3 4 5]


In [152]:
a=np.array([[2,3],[4,5]])
arr=np.vstack(a)
print(arr)

[[2 3]
 [4 5]]


Indexing & slicing



In [158]:
a=[1,3,4,5,2]
result_indices = np.where(np.array(a) == 2)
if result_indices[0].size > 0:
    print("Found")

Found


In [161]:
a=[1,3,4,5,2]
arr=np.take(a,2)
print(arr)

4


In [164]:
a=[1,3,4,5,2]
arr=np.unique(a)
print(arr)

[1 2 3 4 5]


In [170]:
a=[1,3,4,5,2]
arr=np.nonzero(a)
print(arr)

(array([0, 1, 2, 3, 4]),)


In [171]:
a=[1,3,4,5,2]
arr=np.argsort(a)
print(arr)

[0 4 1 2 3]


In [175]:
a=np.array([1,3,4,5,2])
arr=np.split(a,[2])
print(arr)

[array([1, 3]), array([4, 5, 2])]


In [176]:
a=[1,3,4,5,2]
arr=np.flip(a)
print(arr)

[2 5 4 3 1]


In [186]:
a=[1,3,5,2]
arr=np.roll(a, shift=0)
print(arr)

[1 3 5 2]
